import {
  View, Text, ScrollView, StyleSheet, TouchableOpacity, Alert, Platform, ActivityIndicator,
} from 'react-native';
import { useState, useEffect, useCallback } from 'react';
import * as Sharing from 'expo-sharing';
import { C } from '@/constants/colors';
import { supabase } from '@/lib/supabase';

type ReportStats = {
  workDays: number;
  present: number;
  absences: number;
  late: number;
};

type DeptStat = { dept: string; rate: number; color: string };
type TopEmployee = { name: string; email: string; attendanceRate: number; initials: string; color: string; medal: string };

const DEPT_COLORS = ['#3B82F6', '#8B5CF6', '#F59E0B', '#10B981', '#EF4444', '#EC4899'];
const MEDALS = ['🥇', '🥈', '🥉'];

function getInitials(name: string): string {
  return name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2);
}

const MONTH_NAMES = ['January','February','March','April','May','June','July','August','September','October','November','December'];

function buildHtml(stats: ReportStats, deptStats: DeptStat[], topEmployees: TopEmployee[], monthLabel: string) {
  const deptRows = deptStats.map(d => `<tr><td>${d.dept}</td><td class="r b" style="color:${d.color}">${d.rate}%</td></tr>`).join('');
  const perfRows = topEmployees.map((e, i) => `<tr><td>${i === 0 ? '1st' : i === 1 ? '2nd' : '3rd'}</td><td class="b">${e.name}</td><td>${e.email}</td><td class="r b green">${e.attendanceRate}%</td></tr>`).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/>
<style>*{box-sizing:border-box;margin:0;padding:0}body{font-family:Helvetica,Arial,sans-serif;padding:40px;color:#1E293B;font-size:13px;line-height:1.5}.hdr{text-align:center;margin-bottom:32px}.hdr h1{font-size:24px;color:#7C3AED;margin-bottom:4px}.hdr p{font-size:13px;color:#64748B}h2{font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#64748B;border-bottom:1px solid #E2E8F0;padding-bottom:6px;margin:28px 0 14px}.stats{width:100%;border-collapse:separate;border-spacing:8px}.stats td{width:25%;background:#F9FAFB;border:1px solid #E2E8F0;border-radius:8px;padding:16px 8px;text-align:center}.sv{font-size:28px;font-weight:900;margin:4px 0}.sl{font-size:11px;color:#64748B}.blue{color:#3B82F6}.green{color:#10B981}.red{color:#EF4444}.amber{color:#F59E0B}table.d{width:100%;border-collapse:collapse}table.d th,table.d td{padding:10px 12px;text-align:left;border-bottom:1px solid #F1F5F9;font-size:13px}table.d th{background:#F9FAFB;font-weight:700;color:#374151}.r{text-align:right}.b{font-weight:700}.ft{margin-top:40px;text-align:center;font-size:11px;color:#94A3B8;border-top:1px solid #E2E8F0;padding-top:16px}
</style></head><body>
<div class="hdr"><h1>Falcon Memorial Garden</h1><p>Monthly Attendance Report &mdash; ${monthLabel}</p></div>
<h2>Company Overview</h2>
<table class="stats"><tr>
  <td><div class="sv blue">${stats.workDays}</div><div class="sl">Work Days</div></td>
  <td><div class="sv green">${stats.present}</div><div class="sl">Present</div></td>
  <td><div class="sv red">${stats.absences}</div><div class="sl">Absences</div></td>
  <td><div class="sv amber">${stats.late}</div><div class="sl">Late</div></td>
</tr></table>
<h2>Department Attendance</h2>
<table class="d"><tr><th>Department</th><th class="r">Rate</th></tr>${deptRows}</table>
<h2>Top Performers</h2>
<table class="d"><tr><th>Rank</th><th>Employee</th><th>Email</th><th class="r">Attendance</th></tr>${perfRows}</table>
<div class="ft">Generated by Falcon Memorial Garden EMS &bull; ${monthLabel}</div>
</body></html>`;
}

export default function ReportsScreen() {
  const [exporting, setExporting]   = useState(false);
  const [loading, setLoading]       = useState(true);
  const [stats, setStats]           = useState<ReportStats>({ workDays: 0, present: 0, absences: 0, late: 0 });
  const [deptStats, setDeptStats]   = useState<DeptStat[]>([]);
  const [topEmployees, setTopEmployees] = useState<TopEmployee[]>([]);

  const now = new Date();
  const monthLabel = `${MONTH_NAMES[now.getMonth()]} ${now.getFullYear()}`;
  const monthStart = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-01`;
  const nextMonth  = new Date(now.getFullYear(), now.getMonth() + 1, 1);
  const monthEnd   = `${nextMonth.getFullYear()}-${String(nextMonth.getMonth() + 1).padStart(2, '0')}-01`;

  const fetchReports = useCallback(async () => {
    setLoading(true);
    try {
      // Fetch all attendance records for the current month
      const { data: attData } = await supabase
        .from('attendance')
        .select('*, users(id, full_name, email, department)')
        .gte('date', monthStart)
        .lt('date', monthEnd);

      const records = attData ?? [];

      // Count work days in month (Mon-Fri)
      let workDays = 0;
      const d = new Date(monthStart);
      while (d < nextMonth) {
        const day = d.getDay();
        if (day !== 0 && day !== 6) workDays++;
        d.setDate(d.getDate() + 1);
      }

      // Compute stats
      let present = 0, late = 0, absences = 0;
      records.forEach(r => {
        if (!r.time_in) { absences++; return; }
        const h = new Date(r.time_in).getHours();
        const m = new Date(r.time_in).getMinutes();
        if (h > 8 || (h === 8 && m > 15)) late++;
        else present++;
      });

      setStats({ workDays, present, absences, late });

      // Per-employee attendance rate
      const { data: users } = await supabase
        .from('users')
        .select('id, full_name, email, department')
        .eq('role', 'employee');

      const userMap = new Map<string, { name: string; email: string; dept: string; days: number; attended: number }>();
      (users ?? []).forEach(u => userMap.set(u.id, { name: u.full_name, email: u.email, dept: u.department ?? '—', days: workDays, attended: 0 }));

      records.forEach(r => {
        if (r.time_in && userMap.has(r.user_id)) {
          userMap.get(r.user_id)!.attended++;
        }
      });

      // Department stats
      const deptMap = new Map<string, { total: number; attended: number; color: string }>();
      let colorIdx = 0;
      userMap.forEach(u => {
        if (!deptMap.has(u.dept)) {
          deptMap.set(u.dept, { total: 0, attended: 0, color: DEPT_COLORS[colorIdx++ % DEPT_COLORS.length] });
        }
        const d = deptMap.get(u.dept)!;
        d.total += u.days;
        d.attended += u.attended;
      });

      const deptArr: DeptStat[] = [];
      deptMap.forEach((v, dept) => {
        deptArr.push({ dept, rate: v.total > 0 ? Math.round((v.attended / v.total) * 100) : 0, color: v.color });
      });
      setDeptStats(deptArr.sort((a, b) => b.rate - a.rate));

      // Top employees
      const empArr = Array.from(userMap.entries()).map(([, u], i) => ({
        name: u.name,
        email: u.email,
        attendanceRate: u.days > 0 ? Math.round((u.attended / u.days) * 100) : 0,
        initials: getInitials(u.name),
        color: DEPT_COLORS[i % DEPT_COLORS.length],
        medal: MEDALS[i] ?? '',
      }));
      setTopEmployees(empArr.sort((a, b) => b.attendanceRate - a.attendanceRate).slice(0, 3));
    } catch (e) {
      console.error('Failed to fetch reports:', e);
    } finally {
      setLoading(false);
    }
  }, [monthStart, monthEnd]);

  useEffect(() => { fetchReports(); }, [fetchReports]);

  const handleExport = async () => {
    if (exporting) return;
    setExporting(true);
    try {
      const html = buildHtml(stats, deptStats, topEmployees, monthLabel);
      if (Platform.OS === 'web') {
        const blob = new Blob([html], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        window.open(url, '_blank');
        URL.revokeObjectURL(url);
        setExporting(false);
        return;
      }
      const { File, Paths } = await import('expo-file-system');
      const file = new File(Paths.cache, `FMG_Report_${monthLabel.replace(' ', '')}.html`);
      file.write(new TextEncoder().encode(html));
      setExporting(false);
      await Sharing.shareAsync(file.uri);
    } catch (err: any) {
      setExporting(false);
      Alert.alert('Export Failed', err?.message ?? 'Could not export report.');
    }
  };

  const MONTHLY_STATS = [
    { label: 'Work Days', value: String(stats.workDays), icon: '📅', color: '#3B82F6' },
    { label: 'Present',   value: String(stats.present),   icon: '✅', color: '#10B981' },
    { label: 'Absences',  value: String(stats.absences),  icon: '❌', color: '#EF4444' },
    { label: 'Late',      value: String(stats.late),      icon: '⏱️', color: '#F59E0B' },
  ];

  return (
    <ScrollView style={s.container} showsVerticalScrollIndicator={false} contentContainerStyle={s.content}>

      {/* Header */}
      <View style={s.headerRow}>
        <View>
          <Text style={s.pageTitle}>{monthLabel}</Text>
          <Text style={s.pageSub}>Attendance & performance overview</Text>
        </View>
        <TouchableOpacity
          style={[s.exportBtn, exporting && s.exportBtnDim]}
          onPress={handleExport}
          activeOpacity={0.8}
          disabled={exporting}
        >
          {exporting
            ? <ActivityIndicator color="#fff" size="small" />
            : <Text style={s.exportBtnText}>Export PDF</Text>
          }
        </TouchableOpacity>
      </View>

      {loading ? (
        <ActivityIndicator color={C.primary} style={{ marginTop: 40 }} />
      ) : (
        <>
          {/* Stats grid */}
          <View style={s.statsGrid}>
            {MONTHLY_STATS.map((m, i) => (
              <View key={i} style={[s.statCard, { borderTopColor: m.color, borderTopWidth: 3 }]}>
                <Text style={s.statIcon}>{m.icon}</Text>
                <Text style={[s.statValue, { color: m.color }]}>{m.value}</Text>
                <Text style={s.statLabel}>{m.label}</Text>
              </View>
            ))}
          </View>

          {/* Department Attendance */}
          <Text style={s.sectionLabel}>Department Attendance</Text>
          <View style={s.card}>
            {deptStats.length === 0 && (
              <Text style={[s.statLabel, { padding: 16, textAlign: 'center' }]}>No department data yet.</Text>
            )}
            {deptStats.map((d, i) => (
              <View key={i} style={[s.barRow, i > 0 && s.barRowBorder]}>
                <Text style={s.deptName}>{d.dept}</Text>
                <View style={s.barTrack}>
                  <View style={[s.barFill, { width: `${d.rate}%` as any, backgroundColor: d.color }]} />
                </View>
                <Text style={[s.barPct, { color: d.color }]}>{d.rate}%</Text>
              </View>
            ))}
          </View>

          {/* Top Performers */}
          <Text style={s.sectionLabel}>Top Performers</Text>
          <View style={s.card}>
            {topEmployees.length === 0 && (
              <Text style={[s.statLabel, { padding: 16, textAlign: 'center' }]}>No employee data yet.</Text>
            )}
            {topEmployees.map((e, i) => (
              <View key={i} style={[s.perfRow, i > 0 && s.perfRowBorder]}>
                <Text style={s.medal}>{e.medal}</Text>
                <View style={[s.perfAvatar, { backgroundColor: e.color + '18', borderColor: e.color + '50' }]}>
                  <Text style={[s.perfAvatarText, { color: e.color }]}>{e.initials}</Text>
                </View>
                <View style={{ flex: 1 }}>
                  <Text style={s.perfName}>{e.name}</Text>
                  <Text style={s.perfDept}>{e.email}</Text>
                </View>
                <View style={s.pctBadge}>
                  <Text style={s.pctText}>{e.attendanceRate}%</Text>
                </View>
              </View>
            ))}
          </View>
        </>
      )}
    </ScrollView>
  );
}

const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  content: { padding: 16, paddingBottom: 48 },

  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8, marginBottom: 20 },
  pageTitle: { fontSize: 22, fontWeight: '800', color: C.text, letterSpacing: -0.4 },
  pageSub: { fontSize: 12, color: C.textSoft, marginTop: 2 },
  exportBtn: {
    backgroundColor: C.primary, paddingHorizontal: 18, paddingVertical: 11,
    borderRadius: 14, minWidth: 110, alignItems: 'center',
    shadowColor: C.primary, shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3, shadowRadius: 10, elevation: 6,
  },
  exportBtnDim: { opacity: 0.7 },
  exportBtnText: { color: '#fff', fontSize: 13, fontWeight: '700' },

  sectionLabel: {
    fontSize: 11, fontWeight: '800', color: C.textSoft,
    marginTop: 24, marginBottom: 12,
    textTransform: 'uppercase', letterSpacing: 1.4,
  },

  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  statCard: {
    width: '47.5%', backgroundColor: C.card, borderRadius: 16, borderWidth: 1,
    borderColor: C.border, padding: 18, alignItems: 'center',
    shadowColor: C.textSoft, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 3,
  },
  statIcon: { fontSize: 26, marginBottom: 8 },
  statValue: { fontSize: 34, fontWeight: '900' },
  statLabel: { fontSize: 12, color: C.textSoft, marginTop: 4, fontWeight: '500' },

  card: {
    backgroundColor: C.card, borderRadius: 18, borderWidth: 1, borderColor: C.border, overflow: 'hidden',
    shadowColor: C.textSoft, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 3,
  },
  barRow: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 14 },
  barRowBorder: { borderTopWidth: 1, borderTopColor: C.borderLight },
  deptName: { width: 90, fontSize: 12, color: C.textMid, fontWeight: '600' },
  barTrack: { flex: 1, height: 7, backgroundColor: C.borderLight, borderRadius: 4, overflow: 'hidden' },
  barFill: { height: 7, borderRadius: 4 },
  barPct: { width: 40, fontSize: 12, fontWeight: '800', textAlign: 'right' },

  perfRow: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12 },
  perfRowBorder: { borderTopWidth: 1, borderTopColor: C.borderLight },
  medal: { fontSize: 22, width: 28, textAlign: 'center' },
  perfAvatar: { width: 42, height: 42, borderRadius: 21, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' },
  perfAvatarText: { fontSize: 13, fontWeight: '800' },
  perfName: { fontSize: 14, fontWeight: '700', color: C.text },
  perfDept: { fontSize: 11, color: C.textSoft, marginTop: 1 },
  pctBadge: {
    backgroundColor: C.successFaint, borderRadius: 10,
    borderWidth: 1, borderColor: C.successBorder, paddingHorizontal: 10, paddingVertical: 5,
  },
  pctText: { fontSize: 13, fontWeight: '800', color: C.success },
});
